name: Run FoldX

on:
  push:
    branches:
      - run_foldx

jobs:
  run-foldx:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Make FoldX executable
      - name: Set up FoldX
        run: |
          chmod +x tools/foldx5_1Linux64/foldx_20241231

      # Run FoldX
      - name: Run FoldX
        run: |
          cd foldx_all_residues_5rsa_4part
          mkdir -p output_foldx
          ../tools/foldx5_1Linux64/foldx_20241231 -f config.cfg

      # Save FoldX results as an artifact
      - name: Upload FoldX results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: foldx-results
          path: foldx_all_residues_5rsa_4part/output_foldx/

      # Copy results to the repository
      - name: Copy results to the repository
        run: |
          mkdir -p saved_results/foldx_all_residues_5rsa_4part
          cp -r foldx_all_residues_5rsa_4part/output_foldx/* saved_results/foldx_all_residues_5rsa_4part/

      # Commit and push results to the repository
      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add saved_results/foldx_all_residues_5rsa_4part/
          git commit -m "Add FoldX results from workflow run" || echo "No changes to commit"
          git push origin run_foldx

