name: Run FoldX

on:
  push:
    branches:
      - run_foldx

jobs:
  run-foldx:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Make FoldX executable
      - name: Set up FoldX
        run: |
          chmod +x tools/foldx5_1_Linux64/foldx_20241231

      # Run FoldX
      - name: Run FoldX
        run: |
          cd foldx_114
          tools/foldx5_1_Linux64/foldx_20241231 -f config.cfg

      # Save FoldX results as an artifact
      - name: Upload FoldX results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: foldx-results
          path: output_114/

      # Copy results to the repository
      - name: Copy results to the repository
        run: |
          mkdir -p saved_results/foldx
          cp -r output_114/* saved_results/foldx/

      # Commit and push results to the repository
      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add saved_results/foldx/
          git commit -m "Add FoldX results from workflow run" || echo "No changes to commit"
          git push
